### ISSUE TITLE
2.18.0 dependency checker deprecation issue

### ISSUE THREAD

**Issue by bungeye** [peec/ember-transition-helper#12]
"ember-cli-babel": "^5.1.5" installs ember-cli-babel@5.2.4 which has dependency ember-cli-version-checker@1.3.1 introducing deprecation issue with Ember 2.18.0 as per:
[https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902](https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902)

updating ember-cli-babel should resolve

**Comment by jacobq** [comment]
This is fixed in [`master`](https://github.com/peec/ember-transition-helper/blob/e0abecfbf749a31cedf93dd6e5c2cdb00304e98a/package.json#L22) now that #14 was accepted. We are just waiting for the next release to be published.

**Comment by jacobq** [comment]
@bungeye, the [author plans to publish shortly](https://github.com/peec/ember-transition-helper/pull/15#issuecomment-365609994). Could you please confirm that the new release resolves the problem for you?

**Update:** [v1.0.0 has been published to npm now](https://www.npmjs.com/package/ember-transition-helper)

**Comment by bungeye** [comment]
That fixed it @jacobq, thanks very much!
