### ISSUE TITLE
Name change? May be easily confused with ember-route-action-helper

### ISSUE THREAD

**Issue by kategengler** [peec/ember-transition-helper#2]
I think this addon will be easily confused with https://github.com/dockyard/ember-route-action-helper

**Comment by elwayman02** [comment]
I was just about to file an issue for the same reason. I was thinking `ember-transition-helper` would be a much more descriptive name for this addon.

**Comment by elbeezi** [comment]
should also be more discoverable via npm etc.—no link back to repo from https://www.npmjs.com/package/ember-route-action. currently hard to find

**Comment by elwayman02** [comment]
@elbeezy you could pretty easily submit a PR for this. :)

**Comment by elbeezi** [comment]
@elwayman02 👍 will do. harder to submit a PR for name change though 😄

**Comment by peec** [comment]
This has now been renamed to `ember-transition-helper`. Thanks for the heads up. Sorry for delay.
