### ISSUE TITLE
ember-route-action with Ember-cli 1.13.13

### ISSUE THREAD

**Issue by jaichandra** [peec/ember-transition-helper#3]
I see that ember-paper uses this plugin with ember-cli 1.13.13 dependency, But I see a "getOwner is not a function" error on my project. ember-paper project compiles fine though. They don't have a dependency for "ember-getowner-polyfill" as well.

**Comment by peec** [comment]
See https://github.com/rwjblue/ember-getowner-polyfill

This has compability with 1.13
